alg: seq2seq
base_dir: log/seq2seq/ga_hanoi/
data:
  batch_size: 200
  dataset: data/npz/hanoi/ga_hanoi.npz
  test_batch_size: 1
  test_size: 0.2
  valid_size: 0.2
gpu: 0
log_level: INFO
model:
  horizon: 4
  input_dim: 5
  l1_decay: 0
  output_dim: 1
  rnn_layers: 1
  rnn_units: 100
  seq_len: 48
  type: lstm_ed
  verified_percentage: 1
test:
  run_times: 1
  test_monthly: false
train:
  dropout: 0
  epochs: 300
  optimizer: adam
  patience: 15
