alg: seq2seq
base_dir: log/seq2seq/taiwan_xgboost
data:
  batch_size: 200
  dataset: data/npz/taiwan_data_xgboost.npz
  test_batch_size: 1
  test_size: 0.2
  valid_size: 0.2
gpu: 0
log_level: INFO
model:
  horizon: 1
  input_dim: 7
  l1_decay: 0
  output_dim: 1
  rnn_layers: 1
  rnn_units: 100
  seq_len: 48
  type: gru
  verified_percentage: 1
test:
  run_times: 1
train:
  dropout: 0
  epochs: 300
  optimizer: adam
  patience: 20
